# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool: NEW_POOL

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'echo "##vsol[task.setvariable variable=JAVA_HOME]/usr/lib/jvm/default-java" && echo "##vso[task.setvariable.variable=M2_HOME]/opt/maven" && echo"##vso[task.setvariable.variable=MAVEN_HOME]/opt/maven"'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'echo "##vso[task.setvariable.variable=PATH]$(M2_HOME)/bin:$(PATH)"'
- task: Maven@4
  inputs:
    azureSubscription: 'MSDN Platforms Subscription(8d350286-edf6-4a53-b8f7-cfcc76ef61e1)'
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: true
    sqMavenPluginVersionChoice: 'latest'

